name: lspns
description: Local Safety and Public Notice System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.3.0

  # Camera & gallery
  image_picker: ^1.0.7

  # GPS
  geolocator: ^11.0.0

  # Offline caching
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Image display
  cached_network_image: ^3.3.1

  # UUID generation for offline reports
  uuid: ^4.3.3

  # Path for file handling
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true